/**
 * Copy for /admin/for-the-nerds — engineering & stack story (internal).
 */

export const forTheNerdsMeta = {
  title: 'For the nerds — Stack & engineering | Deck Masters AK',
  description:
    'How Deck Masters AK’s site is built: Astro, Zaraz, static reviews pipeline, R2 media, VoC-driven copy architecture, conversion measurement, and Cloudflare automation — in plain language.',
};

export const forTheNerdsHero = {
  eyebrow: 'Engineering',
  h1: 'For the nerds',
  lead: `This site is not a generic page builder template. It is a statically generated, type-aware front end with a deliberate content architecture — built for speed, accessibility, and local SEO. Copy and layouts are grounded in real customer language mined from reviews, and third-party measurement runs through Cloudflare Zaraz so the stack stays fast while ads get trustworthy conversion signals. If you care about how things work under the hood, you are in the right place.`,
};

/** Right-rail “at a glance” — keep values short; details live in cards */
export const stackAtAGlance: { label: string; value: string }[] = [
  { label: 'Framework', value: 'Astro 6 (static)' },
  { label: 'Styling', value: 'Tailwind CSS v4' },
  { label: 'Language', value: 'TypeScript' },
  { label: 'Deploy', value: 'Cloudflare Pages + Functions' },
  { label: 'Third-party tags', value: 'Cloudflare Zaraz (edge)' },
  { label: 'Images', value: 'AVIF / WebP (astro:assets)' },
  { label: 'Project media', value: 'Cloudflare R2 (flat keys)' },
  { label: 'Reviews feed', value: 'DataForSEO → JSON @ build' },
  { label: 'Fresh builds', value: 'GitHub Actions → deploy hook' },
  { label: 'Fonts', value: 'Self-hosted (Astro Fonts)' },
];

export type TechPillar = {
  title: string;
  kicker: string;
  summary: string;
  advantages: string[];
};

export const techPillars: TechPillar[] = [
  {
    title: 'Astro — content-first, minimal JavaScript',
    kicker: 'Static site generation',
    summary:
      'We ship HTML from build time, not a heavy client bundle. Pages load fast because the browser does less work — especially on mobile and slower connections in Alaska.',
    advantages: [
      'Static `output` — predictable builds, easy caching on a CDN, no server runtime to babysit for public pages.',
      'Islands architecture when we need interactivity — most of the site stays zero-JS by default.',
      'File-based routing and `.astro` components keep structure obvious: one URL, one obvious file path.',
    ],
  },
  {
    title: 'Tailwind CSS v4 + design tokens',
    kicker: 'Design system in code',
    summary:
      'Spacing, color, and typography live in one theme layer (`@theme` + `global.css`) so the brand stays consistent — orange, teal accent, cream surfaces — without fighting one-off CSS.',
    advantages: [
      'Utility-first workflow: fast iteration, fewer naming debates, smaller CSS surface than hand-rolled stylesheets.',
      'Vite-powered pipeline (`@tailwindcss/vite`) matches Astro’s build — one toolchain, fast HMR in dev.',
      'Accessible focus styles (`focus-ring`) and sharp corners (`rounded-none`) match the Deck Masters look.',
    ],
  },
  {
    title: 'Typed content, VoC, & site architecture',
    kicker: 'Data modules, not mystery strings',
    summary:
      'Service URLs, parent/child relationships, and hub layouts are driven from typed structures — not copy-pasted slugs across dozens of files. Messaging is informed by voice-of-customer patterns from mined reviews so headlines and proof align with how customers actually talk about the work.',
    advantages: [
      '`siteArchitecture.ts` is the map: category → core hub → child pages — same source the services index and hubs use.',
      'Marketing copy is split into modules (`categoryPageCopy`, `childPageCopy`, VOC bundles) so writers and devs do not step on each other.',
      'Review evidence flows into static `google-reviews.json` (generated by `scripts/sync-reviews.js`) — Wall-of-Love sections read from data, not a bloated third-party widget runtime.',
      'TypeScript catches mistakes at build time: broken imports and bad slugs fail before deploy.',
    ],
  },
  {
    title: 'Images & object storage that respect bandwidth',
    kicker: 'astro:assets + R2',
    summary:
      'Hero and project imagery go through Astro’s asset pipeline: modern formats, responsive sizing, and lazy loading where it makes sense. Large project galleries use flat keys on Cloudflare R2 so Markdown references stay portable and builds pull remotes at compile time — no FTP maze.',
    advantages: [
      'AVIF and WebP output (`astro.config` image formats) — smaller files, better LCP scores.',
      'Explicit `width` / `height` on critical images to reduce layout shift.',
      '`R2_SITE_SLUG` and documented flat key conventions keep multiple sites or envs from stepping on the same bucket layout.',
      'No giant unoptimized JPEGs pretending to be a “gallery.”',
    ],
  },
  {
    title: 'Cloudflare Zaraz — third-party at the edge',
    kicker: 'Tags without tanking Core Web Vitals',
    summary:
      'Analytics and ad platforms attach through Cloudflare Zaraz instead of a pile of blocking browser scripts. Cloudflare injects the loader; the app calls `window.zaraz.track` from small client utilities (`src/lib/zaraz-tracking.ts`) for phone clicks, form leads, and completed sales — fewer competing tag managers, cleaner main thread.',
    advantages: [
      'Tools like GA4, Google Ads, and Meta route through one edge-controlled path instead of each vendor dropping its own heavy snippet.',
      'Custom events stay consistent (`phone_click`, `form_submit`, `sale_complete`) — easier to reason about than opaque GTM spaghetti.',
      'Worker variables in Zaraz can transform fields server-side (e.g. hashed email for enhanced conversions) without exposing raw PII in every browser tag.',
    ],
  },
  {
    title: 'SEO & structured data',
    kicker: 'Machines read what humans see',
    summary:
      'Sitemap generation, canonical URLs, and JSON-LD on key templates help search engines and maps understand the business — without spammy tricks.',
    advantages: [
      '`@astrojs/sitemap` with filters — internal tools and internal-only pages stay out of the public sitemap.',
      'LocalBusiness and related schema where appropriate — consistent NAP with `site.json` and the footer.',
      'Unique titles and descriptions per route — no duplicate thin pages.',
    ],
  },
  {
    title: 'Closed-loop conversions & ad reliability',
    kicker: 'Measurement you can bet Smart Bidding on',
    summary:
      'Pitch decks love “full funnel” — engineering-wise that means labeled conversions that Google Ads (and partners) can trust. The site is wired for enhanced conversions and explicit sale signals: either a protected confirmation route that fires `sale_complete` or a webhook-style flow that lands HTML executing the same client helper — so offline wins still show up as modeled signal, not guesses.',
    advantages: [
      '`sale_complete` and lead events run through Zaraz, matching browser-side tagging with server-forwarded data where tools allow — better deduping and stability than pixels alone.',
      'Quote submissions use a Cloudflare Pages Function (`functions/api/submit-quote.js`) — server-side CRM handoff without shipping another heavyweight SaaS embed on public pages.',
      'Strict vs stale fallback env flags on review sync (`SYNC_REVIEWS_STRICT`, `SKIP_SYNC_REVIEWS`) keep CI predictable when APIs stall — same discipline applies when attribution endpoints must not silently break.',
    ],
  },
  {
    title: 'Automation & fresh proof',
    kicker: 'Scheduled builds',
    summary:
      'Production rebuilds on a schedule so review-driven sections stay current — social proof is not a one-time snapshot from launch day. Unlike embedding a live review widget (extra JavaScript, layout shift, third-party cookies), we compile Google reviews into static JSON at build time via DataForSEO — the HTML visitors get is already fast.',
    advantages: [
      'GitHub Actions (`.github/workflows/scheduled-pages-deploy.yml`) POSTs a Cloudflare Pages deploy hook daily — new reviews land after a normal `npm run build`, not a manual login.',
      '`scripts/sync-reviews.js` polls DataForSEO, downloads avatars, writes `src/data/google-reviews.json` — multi-client ready via `reviews-clients.json`.',
      'Review sync runs at the start of production build; failures can fail the deploy or fall back to committed JSON depending on env — ops-friendly.',
      'Infrastructure-as-code mindset: same build locally and in CI reduces “works on my machine” surprises.',
    ],
  },
];
